#!/bin/bash

set -e

swift build

export DYLD_LIBRARY_PATH=/Library/Developer/Toolchains/swift-latest.xctoolchain/usr/lib/swift/macosx

.build/debug/Tests/Stream/BufferedInputStream
.build/debug/Tests/Stream/BufferedOutputStream
.build/debug/Tests/Stream/BufferedStream
.build/debug/Tests/Stream/BufferedStreamReader
.build/debug/Tests/Stream/BufferedStreamWriter
.build/debug/Tests/Stream/ByteStream
.build/debug/Tests/Stream/MemoryStream
.build/debug/Tests/Stream/Numeric
.build/debug/Tests/Stream/Stream
.build/debug/Tests/Stream/StreamReader
.build/debug/Tests/Stream/SubStreamReader
.build/debug/Tests/Stream/SubStreamWriter
